model:
  _convert_: all
  img_size:
  - 32
  - 128
  max_label_length: 15
  charset_train: 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
  charset_test: 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
  batch_size: 64
  weight_decay: 0.0
  warmup_pct: 0.075
  name: parseq
  _target_: strhub.models.parseq.system.PARSeq
  pretrained: true
  checkpoint: /Users/gulaiymibraimova/ai_app/lpr/models/lpr/evaluated_ocr_model.pt
  patch_size:
  - 4
  - 8
  embed_dim: 384
  enc_num_heads: 6
  enc_mlp_ratio: 4
  enc_depth: 12
  dec_num_heads: 12
  dec_mlp_ratio: 4
  dec_depth: 1
  lr: 1.0e-05
  perm_num: 6
  perm_forward: true
  perm_mirrored: true
  dropout: 0.1
  decode_ar: true
  refine_iters: 1
data:
  _target_: strhub.data.module.SceneTextDataModule
  root_dir: datasets/data_csv_lmdb
  train_dir: train
  val_dir: val
  batch_size: ${model.batch_size}
  img_size: ${model.img_size}
  charset_train: ${model.charset_train}
  charset_test: ${model.charset_test}
  max_label_length: ${model.max_label_length}
  remove_whitespace: true
  normalize_unicode: true
  augment: true
  num_workers: 4
trainer:
  _target_: pytorch_lightning.Trainer
  _convert_: all
  val_check_interval: 1
  max_epochs: 10
  gradient_clip_val: 20
  accelerator: cpu
  devices: 1
  precision: 16-mixed
  gpus: 0
pretrained: parseq
ckpt_path: lpr/models/lpr/evaluated_ocr_model.pt
charset:
  model:
    charset_train: 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
    path: lpr/configs/charset/label.yaml
tune:
  num_samples: 10
  gpus_per_trial: 0.0
  lr:
    min: 1.0e-06
    max: 0.0001
  resume_dir: null
