defaults:
  - main
  - _self_

ckpt_path: lpr/models/lpr/evaluated_ocr_model.pt

trainer:
  devices: 1
  max_epochs: 10


tune:
  num_samples: 10
  gpus_per_trial: 0
  lr:
    min: 1e-4
    max: 2e-3
  resume_dir: null

hydra:
  run:
    dir: ray_results/${model.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
